**Name : Siddharth Kadam**<br>
**ID : 202318015**

#**Task A:**
Develop Python code to perform block multiplication on two given matrices.

In [ ]:
import numpy as np

<h1>Simple Matrix Multiplication</h1>

In [ ]:
def sim_matrix_multiplication(matrix_1,matrix_2):
  matrix_1_row=len(matrix_1) # Total Number of rows in Matrix 1
  matrix_1_column=len(matrix_1[0])# Total Number of columns in Matrix 1
  matrix_2_row=len(matrix_2)# Total Number of rows in Matrix 2
  matrix_2_column=len(matrix_2[0])# Total Number of columns in Matrix 2
  matrix_multi=[] #Empty List to store Result of Multiplication
  if(matrix_1_column==matrix_2_row):
    for m1_r in range(len(matrix_1)): # To iterate Rows in Matrix 1
      temp = [] # to store Values on individual rows temporaraliy
      for m2_c in range(matrix_2_column): # To iterate Columns in Matrix 2
        value=0
        for m1_c in range(matrix_1_column): # To iterate columns in Matrix 1
          value+=(matrix_1[m1_r][m1_c]*matrix_2[m1_c][m2_c])
        temp.append(value)
      matrix_multi.append(temp)
  else:
    print("Multiplication Not Possible!!")
  return matrix_multi

In [ ]:
# Example was taken from Sem - 1 MFDS Assignment
matrix_1=[[1,2,4,1],
          [1,0,-1,-2],
          [2,-1,3,1],
          [1,2,3,4]]
matrix_2=[[-2,2,-3,3],
          [0,1,-1,2],
          [-2,-1,0,1],
          [4,0,1,4]]
np.matrix(sim_matrix_multiplication(matrix_1,matrix_2))

matrix([[-6,  0, -4, 15],
        [-8,  3, -5, -6],
        [-6,  0, -4, 11],
        [ 8,  1, -1, 26]])

<h1> Block Matrix   Multiplication</h1>


In [ ]:
def matrix_multiplication(matrix_1,matrix_2):
  matrix_1_row=len(matrix_1) # Total Number of rows in Matrix 1
  matrix_1_column=len(matrix_1[0])# Total Number of columns in Matrix 1
  matrix_2_row=len(matrix_2)# Total Number of rows in Matrix 2
  matrix_2_column=len(matrix_2[0])# Total Number of columns in Matrix 2
  matrix_multi=[] #Empty List to store Result of Multiplication
  if(matrix_1_column==matrix_2_row):
    for m1_r in range(len(matrix_1)): # To iterate Rows in Matrix 1
      temp = [] # to store Values on individual rows temporaraliy
      for m2_c in range(matrix_2_column):# To iterate Columns in Matrix 2
        value=0
        for m1_c in range(matrix_1_column): # To iterate columns in Matrix 1
          rec_val=[]
          if type(matrix_1[m1_r][m1_c])== np.ndarray: # If Block is there , Not Value (int) we will Recursivly Call Matrix_multiplication method
            rec_val=np.array(matrix_multiplication(matrix_1[m1_r][m1_c],matrix_2[m1_c][m2_c]))
            if type(value)!= np.ndarray: # Means when value = 0
              value=np.array(rec_val)
            else:
              value+=rec_val

          else:
            rec_val=(matrix_1[m1_r][m1_c]*matrix_2[m1_c][m2_c]) # when it is values ,not block
            value+=rec_val
        temp.append(value)
      matrix_multi.append(temp)
  else:
    print("Multiplication Not Possible!!")
  return matrix_multi

In [ ]:
def slice_sub_matrix(matrix_1,matrix_2):
  matrix_len=int(len(matrix_1))
  sub_matrix_size=int(matrix_len/2)
  # Sub matrix Size will Always be len / 2
  # means if Matrix size = 4 ,then Sub-Matrix(block) = 2
  # if Matrix size = 6 ,then Sub-Matrix(block) = 3
  # if Matrix size = 8 ,then Sub-Matrix(block) = 4
  #print(sub_matrix_size)
  mat1=[[matrix_1[0:sub_matrix_size, 0:sub_matrix_size],matrix_1[0:sub_matrix_size, sub_matrix_size:]],
     [matrix_1[sub_matrix_size:, 0:sub_matrix_size],matrix_1[sub_matrix_size:, sub_matrix_size:]]]
  mat2=[[matrix_2[0:sub_matrix_size, 0:sub_matrix_size],matrix_2[0:sub_matrix_size, sub_matrix_size:]],
     [matrix_2[sub_matrix_size:, 0:sub_matrix_size],matrix_2[sub_matrix_size:, sub_matrix_size:]]]


  # After Slicing matrics into 4 Different blocks
  multi_matrix=matrix_multiplication(mat1,mat2)
  #print(multi_matrix)
  # below code is visualise matrix easily
  multi_matrix = np.concatenate([np.concatenate(row, axis=1) for row in multi_matrix], axis=0)

  print(multi_matrix)



In [ ]:
# Example was taken from Sem - 1 MFDS Assignment
matrix_1=np.array([[1,2,4,1],
          [1,0,-1,-2],
          [2,-1,3,1],
          [1,2,3,4]])
matrix_2=np.array([[-2,2,-3,3],
          [0,1,-1,2],
          [-2,-1,0,1],
          [4,0,1,4]])
#print(matrix_multiplication2(matrix_1,matrix_2))
slice_sub_matrix(matrix_1,matrix_2)




[[-6  0 -4 15]
 [-8  3 -5 -6]
 [-6  0 -4 11]
 [ 8  1 -1 26]]


In [ ]:
matrix_1=np.array([
    [1,0,0,0,0,0,0,0],
    [0,1,0,0,0,0,0,0],
    [0,0,1,0,0,0,0,0],
    [0,0,0,1,0,0,0,0],
    [0,0,0,0,1,0,0,0],
    [0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,1],
    ])

matrix_2=np.array([
    [1,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0],
    [1,0,1,0,0,0,0,0],
    [1,0,0,1,0,0,0,0],
    [1,0,0,2,1,0,0,0],
    [1,0,0,0,0,1,0,0],
    [1,0,0,2,0,0,1,0],
    [1,0,0,2,0,0,0,1],
    ])
#print(matrix_multiplication2(matrix_1,matrix_2))
slice_sub_matrix(matrix_1,matrix_2)


[[1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]
 [1 0 0 2 1 0 0 0]
 [1 0 0 0 0 1 0 0]
 [1 0 0 2 0 0 1 0]
 [1 0 0 2 0 0 0 1]]


#**Task B:**
This segment of the assignment is designed to enhance your understanding of the API
call process and dataset creation. Utilize any freely available API endpoint on Rapidapi to
generate a dataset.

In [ ]:
pip install requests

In [ ]:
# This API only provides 20 calls and i have use it all , so it may give error to call the API

import requests
import csv


# Function to get data from the Amazon Product API and save it to a CSV file
def get_api_data(product_name,file_name,pages=1):
   # API endpoint URL
  url = "https://amazon-product-data6.p.rapidapi.com/product-by-text"


  headers = {
    "X-RapidAPI-Key": "2471033d50msh4cef20a0ee724e4p192c16jsn0e55e68aaa3e",
	  "X-RapidAPI-Host": "amazon-product-data6.p.rapidapi.com"
  }
  for i in range(1,pages+1):
    # Parameters for the API request
    querystring = {"keyword": product_name , "page": str(i), "country": "US"}
     # Sending  a GET request to the API
    response = requests.get(url, headers=headers, params=querystring)
    #print(response.json())
    # Check if the request was successful (status code 200)
    if response.status_code == 200:
           # Extracting data from the JSON response
        data = response.json().get("data", [])

        # Check if there is any data
        if data:
            # Define the CSV file path
            csv_file_path = file_name

            # Write the data to a CSV file
            with open(csv_file_path, "a", newline="", encoding="utf-8") as csv_file:
                 # Defining the CSV fieldnames (column headers)
                fieldnames = [
                    "asin",
                    "title",
                    "url",
                    "image",
                    "price",
                    "original_price",
                    "stars",
                    "rating_count",
                    "bought_in_past_month",
                    "is_prime",
                    "is_best_seller",
                    "is_climate_pledge_friendly",
                    "is_limited_time_deal",
                    "is_sponsored",
                ]

                writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
                writer.writeheader()
                # Writing each item's data as a row in the CSV file
                for item in data:
                    writer.writerow(item)

            print("Dataset created : {csv_file_path}")
        else:
            print("No data received from the API.")
    else:
        print(f"Error: API Response Error")


product_name=input("Enter Product Name:")
pages=int(input("Enter total Number of pages:"))
file_name=input("Enter the file name ie File_name.csv :")

get_api_data(product_name,file_name,pages)

In [ ]:
import pandas as pd

df=pd.read_csv(file_name)
df

#**Task C:**
In this part of the assignment, you will learn how to construct a dataset by scraping a
website online. Utilize BeautifulSoup or any other suitable scraping library to extract all the
details of Amazon products and compile a dataset.

In [1]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
import time


In [17]:
def web_scrap_amazon(search_keyword, num_pages):
    base_url = 'https://www.amazon.in/s'
    data = []

    for page in range(1, num_pages + 1):
        params = {'k': search_keyword, 'page': page}
        webpage = requests.get(base_url, params=params)
        soup = bs(webpage.content, 'html.parser')
           # Finding  all product containers on the page
        products=soup.find_all('div',class_='puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v1x9xtdrqwkf2b2sy3gv3bhvhpn s-latency-cf-section puis-card-border')

        # Loop through each product container
        for product in products:

            brand_name = product.find('h2').text.strip()
            rating = product.find('span', class_='a-icon-alt').text.strip() if product.find('span', class_='a-icon-alt') else 'N/A'
            reviews = product.find('span', class_='a-size-base s-underline-text').text.strip() if product.find('span', class_='a-size-base s-underline-text') else 'N/A'
            price = product.find('span', class_='a-price-whole').text.strip() if product.find('span', class_='a-price-whole') else 'N/A'

             # Append the extracted data to the 'data' list
            data.append({'brand_name': brand_name,'rating': rating, 'reviews': reviews, 'price': price})

    # Converting the list of dictionaries to a Pandas DataFrame
    return pd.DataFrame(data)



In [18]:
# Amazon Web Scrapping
search_keyword = input("Enter the product Name:")
num_pages_to_scrape = int(input("Enter the Total number pages to scrap(More the 4 pages) :"))
df = web_scrap_amazon(search_keyword, num_pages_to_scrape)
df.to_csv(search_keyword+'.csv',index=True)

Enter the product Name:oneplus 
Enter the Total number pages to scrap(More the 4 pages) :10


In [19]:
df1 = pd.read_csv(search_keyword+'.csv')
df1

Unnamed: 0                                         brand_name  \
0            0  7SEVEN® Infrared Non Voice oneplus Remote | 1+...   
1            1  ZARALA Back Camera Lens Protector For OnePlus ...   
2            2  7SEVEN® Bluetooth Voice Command Remote Compati...   
3            3  Sounce Case Silicone Cover, Compatible with Ke...   
4            4  (Refurbished) OnePlus Buds Pro 2 Bluetooth Tru...   
5            5  Robustrion Tempered Glass Screen Protector Gua...   
6            6  Caldipree Silicone Remote Cover Case Pouch Com...   
7            7  OnePlus 10R 5G Prime Edition (Prime Blue, 8GB ...   
8            8  amazon basics Case for OnePlus Nords Buds, TWS...   
9            9  ZdalaMit Compatible Bluetooth Voice Command (G...   
10          10  ProElite Keyboard case for OnePlus Pad Go 11.3...   
11          11  OnePlus Nord N20 SE (Jade Wave, 4GB RAM, 128GB...   
12          12  VEROX Adjustable Replacement Band Compatible w...   
13          13  (Refurbished) OnePlus 7 (Mirror Grey, 6GB RAM ...   
14          14  Mavro Case Cover Compatible with OnePlus Buds ...   
15          15  Sounce White Adjustable Band Strap Compatible ...   
16          16  Amozo OnePlus 11R 5G Back Cover | Slim Fabric ...   
17          17  Mavro Case Cover Compatible with OnePlus Buds ...   
18          18  Amazon Basics Case for OnePlus Nord Buds, TWS ...   
19          19  RIGGEAR Shockproof Sleek Hybrid Armor Back Cov...   
20          20  (Refurbished) OnePlus Nord CE 5G (Charcoal Ink...   
21          21  RAYA Silicone Protective Full Wrap Remote Case...   
22          22  OnePlus Buds Pro 2 | 2R (2023) Silicone Skin C...   
23          23  Sounce Light Blue Adjustable Band Strap Compat...   
24          24  Oboe Silicone TV Remote Cover Compatible with ...   
25          25  camera Lens Protector for OnePlus 12 5G, 9H Ha...   
26          26  INEFABLE Oneplus Band Strap and Oppo Band Stra...   
27          27  OnePlus Buds Z2 Bluetooth Truly Wireless in Ea...   
28          28  Caldipree Silicone Remote Cover Case Pouch Com...   
29          29  (Refurbished) OnePlus 6T (Mirror Black, 6GB RA...   
30          30  RAYA Silicone Protective Full Wrap Remote Case...   
31          31  TECHSHIELD Tempered Glass Screen Protector for...   

                rating reviews   price  
0   3.7 out of 5 stars     234     389  
1   4.2 out of 5 stars      23     279  
2   3.5 out of 5 stars     264     899  
3   4.1 out of 5 stars   5,004     199  
4   3.3 out of 5 stars       5   9,348  
5   4.1 out of 5 stars     263     399  
6   4.3 out of 5 stars      67     299  
7   4.3 out of 5 stars  18,776  34,999  
8   3.8 out of 5 stars     419     149  
9   4.7 out of 5 stars   1,844   1,079  
10                 NaN     NaN   2,799  
11  5.0 out of 5 stars       2  14,500  
12  3.8 out of 5 stars     229     199  
13  3.1 out of 5 stars      15  11,499  
14  4.1 out of 5 stars     584     299  
15  3.9 out of 5 stars   4,285     199  
16  4.3 out of 5 stars     121     379  
17  4.1 out of 5 stars     584     299  
18  3.8 out of 5 stars     419     105  
19  4.3 out of 5 stars     488     367  
20  2.5 out of 5 stars       9  16,444  
21  5.0 out of 5 stars       1     250  
22  3.8 out of 5 stars     200     399  
23  3.9 out of 5 stars   4,285     199  
24  4.4 out of 5 stars   1,059     379  
25                 NaN     NaN     239  
26  3.8 out of 5 stars     728     141  
27  4.2 out of 5 stars  23,333   5,999  
28  4.3 out of 5 stars      67     299  
29  3.1 out of 5 stars       7  10,999  
30  5.0 out of 5 stars       1     250  
31  3.0 out of 5 stars       3     499